import generatedPeaks from './peaks.json';

export interface Track {
  id: string;
  title: string;
  /** Optional secondary line: remix credit, feature, release name. */
  subtitle?: string;
  year: number;
  /** Runtime in seconds, read from the file itself. */
  duration: number;
  /** Path under public/, e.g. /music/hellfire.mp3 */
  src: string;
  /** Path under public/, e.g. /music/covers/hellfire.jpg */
  cover: string;
  /** Folder slug this track lives in. Absent for singles. */
  album?: string;
  /** Display name of the album, from the ID3 tag when it has one. */
  albumTitle?: string;
  /** Track number inside its album. */
  trackNo?: number;
  /** Peak values 0..1, one per waveform bar. */
  peaks: number[];
  /** False until the real file has been analysed. */
  hasRealPeaks: boolean;
  /** Set false to hide the download button for a single track. */
  downloadable?: boolean;
  tags?: string[];
}

export interface Release {
  /** Album slug, or undefined for the loose singles group. */
  album?: string;
  title: string;
  year: number;
  cover: string;
  tracks: Track[];
}

/** Placeholder shape used when a track has no generated peaks yet. */
const placeholderPeaks = (seed: number, bars = 120) =>
  Array.from({ length: bars }, (_, i) => {
    const wave = Math.sin((i + seed) * 0.28) * 0.5 + 0.5;
    const detail = Math.sin((i + seed) * 1.7) * 0.22;
    return Math.min(1, Math.max(0.08, wave * 0.72 + detail + 0.18));
  });

const generated = generatedPeaks as Record<string, number[]>;

const peaksFor = (id: string, seed: number) => generated[id] ?? placeholderPeaks(seed);
const hasPeaks = (id: string) => Boolean(generated[id]?.length);

// Generated by `bun run music`. title/year/duration/cover/album come from the
// files; subtitle, tags and downloadable are kept across runs.
export const tracks: Track[] = [
  {
    id: 'whisper-your-name',
    title: 'whisper your name',
    year: 2026,
    duration: 79,
    src: 'no memory/whisper your name.mp3',
    cover: '/music/covers/no memory.jpg',
    album: 'no memory',
    albumTitle: 'no memory pt. 1',
    trackNo: 1,
    peaks: peaksFor('whisper-your-name', 119),
    hasRealPeaks: hasPeaks('whisper-your-name'),
  },
  {
    id: 'can-you-breathe',
    title: 'can you breathe? (ft. Alison Wales)',
    year: 2026,
    duration: 251,
    src: 'no memory/can you breathe.mp3',
    cover: '/music/covers/no memory.jpg',
    album: 'no memory',
    albumTitle: 'no memory pt. 1',
    trackNo: 2,
    peaks: peaksFor('can-you-breathe', 105),
    hasRealPeaks: hasPeaks('can-you-breathe'),
  },
  {
    id: 'being-abstract',
    title: 'being abstract',
    year: 2026,
    duration: 188,
    src: 'no memory/being abstract.mp3',
    cover: '/music/covers/no memory.jpg',
    album: 'no memory',
    albumTitle: 'no memory pt. 1',
    trackNo: 3,
    peaks: peaksFor('being-abstract', 98),
    hasRealPeaks: hasPeaks('being-abstract'),
  },
];

/** Albums first, then whatever is left over as singles. */
export const releases: Release[] = (() => {
  const albums = new Map<string, Release>();
  const singles: Track[] = [];

  for (const track of tracks) {
    if (!track.album) {
      singles.push(track);
      continue;
    }

    const existing = albums.get(track.album);
    if (existing) {
      existing.tracks.push(track);
      existing.year = Math.max(existing.year, track.year);
    } else {
      albums.set(track.album, {
        album: track.album,
        title: track.albumTitle ?? track.album,
        year: track.year,
        cover: track.cover,
        tracks: [track],
      });
    }
  }

  const grouped = [...albums.values()].sort((a, b) => b.year - a.year);

  if (singles.length) {
    grouped.push({
      title: singles.length === tracks.length ? "tracks" : "singles",
      year: Math.max(...singles.map((t) => t.year)),
      cover: singles[0].cover,
      tracks: singles,
    });
  }

  return grouped;
})();
